import { expect, test } from "@playwright/test";
const session={user:{id:1,email:"test@aura.local",full_name:"Test Executive",role:"user"},organization:{id:1,name:"Aura Test"},workspace:{id:1,name:"Strategy"}};
async function monitor(page){const errors=[],failures=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error"&&!m.text().includes("401 (Unauthorized)"))errors.push(m.text());});page.on("response",r=>{if(r.status()>=400&&!r.url().includes("/auth/login"))failures.push(`${r.status()} ${r.url()}`);});await page.route("http://127.0.0.1:8000/**",r=>r.fulfill({status:200,contentType:"application/json",body:"{}"}));return {errors,failures};}
async function authenticate(page){await page.evaluate(()=>localStorage.setItem("aura_token","test-token"));await page.route("http://127.0.0.1:8000/auth/me",r=>r.fulfill({contentType:"application/json",body:JSON.stringify(session)}));await page.route("http://127.0.0.1:8000/organizations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({organizations:[session.organization]})}));await page.route("http://127.0.0.1:8000/dashboard",r=>r.fulfill({contentType:"application/json",body:"{}"}));}
test("landing page navigation, keyboard focus, and responsive layouts",async({page})=>{const m=await monitor(page);await page.goto("/");await expect(page.getByRole("heading",{name:"Aura OS"})).toBeVisible();await expect(page.getByRole("link",{name:"Launch Aura"})).toBeVisible();await expect(page.getByRole("link",{name:"Learn More"})).toBeVisible();await page.keyboard.press("Tab");await expect(page.locator(":focus")).toBeVisible();for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){await page.setViewportSize(viewport);expect(await page.locator("body").evaluate(body=>body.scrollWidth<=window.innerWidth)).toBeTruthy();}expect(m.errors).toEqual([]);expect(m.failures).toEqual([]);});
test("login and registration validate safely without a live backend",async({page})=>{const m=await monitor(page);await page.goto("/login");const loginPassword=page.getByLabel("Password",{exact:true});await expect(page.getByLabel("Email Address")).toBeVisible();await expect(loginPassword).toBeVisible();await page.getByRole("button",{name:"Show"}).click();await expect(loginPassword).toHaveAttribute("type","text");await page.getByRole("button",{name:"Sign In"}).click();expect(await page.getByLabel("Email Address").evaluate(input=>!input.validity.valid)).toBeTruthy();await page.route("http://127.0.0.1:8000/auth/login",r=>r.fulfill({status:401,contentType:"application/json",body:JSON.stringify({detail:"Invalid login credentials."})}));await page.getByLabel("Email Address").fill("test@aura.local");await loginPassword.fill("incorrect-password");await page.getByRole("button",{name:"Sign In"}).click();await expect(page.getByRole("alert")).toContainText("Invalid login credentials.");await page.goto("/register");await expect(page.getByLabel("Full name")).toBeVisible();await page.getByLabel("Full name").fill("Test Executive");await page.getByLabel("Work email").fill("test@aura.local");await page.getByLabel("Password",{exact:true}).fill("Password1!");await page.getByLabel("Confirm password",{exact:true}).fill("different");await page.getByRole("button",{name:"Create Account"}).click();await expect(page.getByRole("alert")).toContainText("accept the terms");await page.getByRole("checkbox").check();await page.getByRole("button",{name:"Create Account"}).click();await expect(page.getByRole("alert")).toContainText("Passwords do not match.");expect(m.errors).toEqual([]);});
test("protected routing, persistence, shell controls, and logout",async({page})=>{await page.goto("/dashboard");await expect(page).toHaveURL(/\/login$/);await authenticate(page);await page.goto("/dashboard");await expect(page).toHaveURL(/\/dashboard$/);await expect(page.getByRole("link",{name:"Home"})).toBeVisible();await expect(page.locator("input[aria-label='Search Aura']")).toBeVisible();await page.reload();await expect(page).toHaveURL(/\/dashboard$/);await page.getByRole("button",{name:"Logout"}).click();await expect(page).toHaveURL(/\/login$/);expect(await page.evaluate(()=>localStorage.getItem("aura_token"))).toBeNull();await page.goto("/dashboard");await expect(page).toHaveURL(/\/login$/);});

test("auth restoration validates stored tokens and keeps the landing page public",async({page})=>{await page.goto("/");await page.evaluate(()=>localStorage.setItem("aura_token","stale-token"));await page.route("http://127.0.0.1:8000/auth/me",r=>r.fulfill({status:401,contentType:"application/json",body:JSON.stringify({detail:"Invalid token"})}));await page.goto("/dashboard");await expect(page).toHaveURL(/\/login$/);expect(await page.evaluate(()=>localStorage.getItem("aura_token"))).toBeNull();await page.goto("/");await expect(page.getByRole("heading",{name:"Aura OS"})).toBeVisible();});

test("a validated user without an organization is sent to setup",async({page})=>{await page.goto("/");await page.evaluate(()=>localStorage.setItem("aura_token","setup-token"));await page.route("http://127.0.0.1:8000/auth/me",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({user:session.user,organization:null,workspace:null})}));await page.route("http://127.0.0.1:8000/organizations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({organizations:[]})}));await page.goto("/dashboard");await expect(page).toHaveURL(/\/setup$/);});

test("a validated organization without an accessible workspace is sent to setup",async({page})=>{await page.goto("/");await page.evaluate(()=>localStorage.setItem("aura_token","workspace-setup-token"));await page.route("http://127.0.0.1:8000/auth/me",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({user:session.user,organization:session.organization,workspace:null})}));await page.route("http://127.0.0.1:8000/organizations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({organizations:[session.organization]})}));await page.goto("/dashboard");await expect(page).toHaveURL(/\/setup$/);});

test("unknown routes preserve the correct public or protected boundary",async({page})=>{await page.goto("/unknown-public");await expect(page).toHaveURL(/\/$/);await authenticate(page);await page.goto("/unknown-protected");await expect(page).toHaveURL(/\/dashboard$/);});

test("authenticated shell preserves context, focus, and responsive overlays",async({page})=>{const m=await monitor(page);await page.goto("/");await authenticate(page);await page.goto("/dashboard");await expect(page.getByLabel("Current organization: Aura Test")).toBeVisible();await expect(page.getByLabel("Current workspace: Strategy")).toBeVisible();await expect(page.getByText("Guest User")).toHaveCount(0);for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]){await page.setViewportSize(viewport);const profile=page.getByRole("button",{name:"Open profile menu"});await profile.click();const menu=page.getByRole("menu",{name:"Profile menu"});await expect(menu).toContainText("Test Executive");const box=await menu.boundingBox();expect(box.x>=0&&box.y>=0&&box.x+box.width<=viewport.width&&box.y+box.height<=viewport.height).toBeTruthy();expect(await page.locator("body").evaluate(body=>body.scrollWidth<=window.innerWidth)).toBeTruthy();await page.keyboard.press("Escape");await expect(menu).toHaveCount(0);await expect(profile).toBeFocused();if(viewport.width===390){const trigger=page.getByRole("button",{name:"Open navigation"});await trigger.click();const close=page.getByRole("button",{name:"Close navigation",exact:true});await expect(close).toBeFocused();expect(await page.locator("body").evaluate(body=>body.scrollWidth<=window.innerWidth)).toBeTruthy();await page.keyboard.press("Escape");await expect(close).not.toBeVisible();await expect(trigger).toBeFocused();await trigger.click();await page.mouse.click(350,300);await expect(trigger).toBeFocused();await trigger.click();await page.getByRole("link",{name:"Decision Center"}).click();await expect(page).toHaveURL(/\/intelligence$/);await expect(page.getByLabel("Close navigation overlay")).toHaveCount(0);}}expect(m.errors).toEqual([]);expect(m.failures).toEqual([]);});
