import { expect, test } from "@playwright/test";
const personal={user:{id:2,email:"person@aura.local",full_name:"Personal User"},organization:{id:2,name:"Personal Space",account_type:"personal"},workspace:{id:2,name:"My Workspace"},product_mode:"personal",capabilities:["home","personal_home","ask_aura","decisions","documents"]};
async function auth(page){await page.addInitScript(()=>{localStorage.setItem("aura_token","test");localStorage.setItem("aura_personal_conversation_id","77");});await page.route("**/auth/me",r=>r.fulfill({contentType:"application/json",body:JSON.stringify(personal)}));await page.route("**/organizations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({organizations:[personal.organization]})}));}

test("New Conversation clears only the active thread and starts without the prior session id",async({page})=>{
  await auth(page);let request;
  await page.route("**/personal/ask/77",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({session_id:77,mode:"CONVERSATION",turns:[{role:"user",content:"Old thought",mode:"USER"},{role:"assistant",content:"Old answer",mode:"GENERAL"}]})}));
  await page.route("**/personal/ask",async r=>{request=r.request().postDataJSON();await r.fulfill({contentType:"application/json",body:JSON.stringify({mode:"GENERAL",session_id:88,message:"Fresh answer",turns:[{role:"user",content:request.message,mode:"USER"},{role:"assistant",content:"Fresh answer",mode:"GENERAL"}]})});});
  await page.goto("/intelligence");await expect(page.getByText("Old answer")).toBeVisible();await page.getByRole("button",{name:"New Conversation"}).first().click();await expect(page.getByRole("heading",{name:"What's on your mind?"})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem("aura_personal_conversation_id"))).toBeNull();
  await page.getByLabel("Message Aura").fill("Fresh thought");await page.getByRole("button",{name:"Send"}).click();await expect.poll(()=>request).toEqual({message:"Fresh thought"});
});

test("Personal profile owns Settings and Logout without a persistent sidebar logout",async({page})=>{
  await auth(page);await page.route("**/personal/decisions",r=>r.fulfill({contentType:"application/json",body:"[]"}));await page.goto("/dashboard");await expect(page.getByLabel("Primary navigation").getByRole("button",{name:"Logout"})).toHaveCount(0);await page.getByRole("button",{name:"Open profile menu"}).click();await page.getByRole("menuitem",{name:"Settings"}).click();await expect(page).toHaveURL(/\/account$/);await expect(page.getByRole("heading",{name:"Settings"})).toBeVisible();await page.getByRole("button",{name:"Open profile menu"}).click();await page.getByRole("menuitem",{name:"Logout"}).click();await expect(page).toHaveURL(/\/login$/);
});

test("Forgot password uses neutral Alpha-safe delivery messaging",async({page})=>{
  await page.route("**/auth/password-reset/request",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({message:"If an account exists for that email, the password reset request has been accepted.",delivery_configured:false})}));
  await page.goto("/login");await page.getByRole("link",{name:"Forgot password?"}).click();await page.getByLabel("Email Address").fill("person@aura.local");await page.getByRole("button",{name:"Request reset"}).click();await expect(page.getByRole("status")).toContainText("If an account exists");await expect(page.getByRole("status")).toContainText("No email was sent");
});

test("Conversations lists, reopens, and continues the selected owned session",async({page})=>{
  await auth(page);let continued;
  await page.route("**/personal/conversations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify([{session_id:41,title:"Going back to school",preview:"Long-term career growth",message_count:2,updated_at:"2026-08-15T12:00:00Z"},{session_id:52,title:"Plan my evening",preview:"Prepare lunch",message_count:2,updated_at:"2026-08-14T12:00:00Z"}])}));
  await page.route("**/personal/ask/41",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({session_id:41,mode:"CONVERSATION",turns:[{role:"user",content:"Going back to school",mode:"USER"},{role:"assistant",content:"What outcome matters most?",mode:"GENERAL"}]})}));
  await page.route("**/personal/ask",async r=>{continued=r.request().postDataJSON();await r.fulfill({contentType:"application/json",body:JSON.stringify({session_id:41,mode:"GENERAL",message:"Let's compare the paths.",turns:[{role:"user",content:"Going back to school",mode:"USER"},{role:"assistant",content:"What outcome matters most?",mode:"GENERAL"},{role:"user",content:continued.message,mode:"USER"},{role:"assistant",content:"Let's compare the paths.",mode:"GENERAL"}]})});});
  await page.goto("/conversations");await expect(page.getByRole("heading",{name:"Conversations"})).toBeVisible();await page.getByRole("link",{name:/Going back to school/}).click();await expect(page.getByText("What outcome matters most?")).toBeVisible();await page.getByLabel("Message Aura").fill("Long-term growth matters most.");await page.getByRole("button",{name:"Send"}).click();await expect.poll(()=>continued).toEqual({session_id:41,message:"Long-term growth matters most."});
});

test("Conversations empty state and Home summaries hide internal provenance",async({page})=>{
  await auth(page);await page.route("**/personal/conversations",r=>r.fulfill({contentType:"application/json",body:"[]"}));await page.goto("/conversations");await expect(page.getByText("Your conversations with Aura will appear here.")).toBeVisible();
  await page.route("**/personal/decisions",r=>r.fulfill({contentType:"application/json",body:JSON.stringify([{id:9,title:"Buying a car [user-query]",status:"open",recommendation:"Choose a cheaper car [derived:savings_after_purchase]. Keep emergency savings intact while comparing reliable options in detail across several paragraphs that should remain on the decision detail page.",updated_at:"2026-08-15T12:00:00Z"}])}));await page.goto("/dashboard");await expect(page.getByText("Buying a car")).toBeVisible();await expect(page.locator("body")).not.toContainText("[derived:");await expect(page.locator("body")).not.toContainText("[user-query]");await expect(page.getByText(/Choose a cheaper car/)).toBeVisible();
});

test("Conversations remains accessible without overflow at required viewports",async({page})=>{
  await auth(page);await page.route("**/personal/conversations",r=>r.fulfill({contentType:"application/json",body:JSON.stringify([{session_id:41,title:"A bounded conversation title",preview:"A useful preview",message_count:4,updated_at:"2026-08-15T12:00:00Z"}])}));
  for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1024,height:768},{width:1366,height:768},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto("/conversations");await expect(page.getByRole("heading",{name:"Conversations"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);}
});

test("Current Intelligence renders verified sources safely and responsively",async({page})=>{
  await auth(page);await page.route("**/personal/ask/77",r=>r.fulfill({status:404,body:"{}"}));await page.route("**/personal/ask",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({mode:"CURRENT_COMPLETE",session_id:91,message:"The Bank held its policy rate at 2.5% today. [1]",sources:[{id:"1",title:"Policy interest rate announcement with a long wrapping source title",url:"https://bankofcanada.ca/rate",domain:"bankofcanada.ca",published_at:"2026-08-15T12:00:00Z",retrieved_at:"2026-08-15T12:05:00Z"},{id:"2",title:"Unsafe",url:"javascript:alert(1)",domain:"unsafe.test",retrieved_at:"2026-08-15T12:05:00Z"}],turns:[{role:"user",content:"What are current rates?",mode:"USER"},{role:"assistant",content:"The Bank held its policy rate at 2.5% today. [1]",mode:"CURRENT_COMPLETE",payload:{sources:[{id:"1",title:"Policy interest rate announcement with a long wrapping source title",url:"https://bankofcanada.ca/rate",domain:"bankofcanada.ca",published_at:"2026-08-15T12:00:00Z",retrieved_at:"2026-08-15T12:05:00Z"},{id:"2",title:"Unsafe",url:"javascript:alert(1)",domain:"unsafe.test"}]}}]})}));
  for(const viewport of [{width:390,height:844},{width:1920,height:1080}]){await page.setViewportSize(viewport);await page.goto("/intelligence",{waitUntil:"networkidle"});await page.getByLabel("Message Aura").fill("What are current rates?");await page.getByRole("button",{name:"Send"}).click();await expect(page.getByText("Current · verified sources")).toBeVisible();const source=page.locator('a[href="https://bankofcanada.ca/rate"]');await expect(source).toHaveAccessibleName(/Policy interest rate/);await expect(source).toHaveAttribute("rel","noopener noreferrer");await expect(page.getByRole("link",{name:/Unsafe/})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.evaluate(()=>localStorage.removeItem("aura_personal_conversation_id"));}
});

test("Current unavailable state never renders fabricated sources",async({page})=>{
  await auth(page);await page.route("**/personal/ask/77",r=>r.fulfill({status:404,body:"{}"}));await page.route("**/personal/ask",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({mode:"CURRENT_INFORMATION_UNAVAILABLE",session_id:92,message:"I can't verify current information right now.",sources:[],turns:[{role:"user",content:"Latest news?",mode:"USER"},{role:"assistant",content:"I can't verify current information right now.",mode:"CURRENT_INFORMATION_UNAVAILABLE",payload:{sources:[]}}]})}));await page.goto("/intelligence");await page.getByLabel("Message Aura").fill("Latest news?");await page.getByRole("button",{name:"Send"}).click();await expect(page.getByText("I can't verify current information right now.")).toBeVisible();await expect(page.getByRole("heading",{name:"Sources"})).toHaveCount(0);
});
