import { CreditCard, FileText, ReceiptText, RefreshCcw } from "lucide-react";
import { useEffect, useState } from "react";
import { getBillingAccounts, getCreditNotes, getInvoices, getRefunds, getSubscriptions, getUsageRecords } from "../services/api";

const formatValue = (value) => value === null || value === undefined || value === "" ? "—" : String(value);
export default function BillingPage() {
  const [data, setData] = useState({}); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([getBillingAccounts(), getSubscriptions(), getUsageRecords(), getInvoices(), getRefunds(), getCreditNotes()]).then(([accounts, subscriptions, usage, invoices, refunds, creditNotes]) => setData({ accounts, subscriptions, usage, invoices, refunds, creditNotes })).catch(() => setError("Billing information could not be loaded. Please try again.")).finally(() => setLoading(false)); }, []);
  const list = (value) => Array.isArray(value) ? value : [];
  const sections = [{ title: "Billing account", icon: CreditCard, rows: list(data.accounts), fields: ["billing_name", "billing_email", "currency", "status"] }, { title: "Subscription", icon: RefreshCcw, rows: list(data.subscriptions), fields: ["status", "plan_id", "starts_at", "ends_at"] }, { title: "Usage", icon: ReceiptText, rows: list(data.usage), fields: ["feature_key", "quantity", "occurred_at"] }, { title: "Invoices", icon: FileText, rows: list(data.invoices), fields: ["invoice_number", "status", "total", "outstanding_balance"] }, { title: "Refunds", icon: ReceiptText, rows: list(data.refunds), fields: ["status", "amount", "currency"] }, { title: "Credit notes", icon: FileText, rows: list(data.creditNotes), fields: ["credit_note_number", "status", "amount"] }];
  return <section className="mx-auto max-w-7xl"><header><p className="text-sm font-semibold text-blue-400">Commercial platform</p><h1 className="mt-2 text-3xl font-semibold text-white">Billing</h1><p className="mt-2 text-slate-400">Billing information for the active organization.</p></header>{loading ? <p className="py-16 text-center text-slate-400">Loading billing workspace…</p> : error ? <p role="alert" className="mt-8 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-red-100">{error}</p> : <div className="mt-8 grid gap-5 lg:grid-cols-2">{sections.map(({ title, icon: Icon, rows, fields }) => <section key={title} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><header className="flex items-center gap-2 border-b border-white/10 px-5 py-4"><Icon size={18} className="text-blue-300"/><h2 className="font-medium text-white">{title}</h2></header>{rows.length === 0 ? <p className="p-5 text-sm text-slate-400">No {title.toLowerCase()} records are available.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr>{fields.map((field) => <th key={field} className="px-5 py-3 font-medium">{field.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.slice(0, 5).map((row, index) => <tr key={row.id || index} className="border-t border-white/5 text-slate-300">{fields.map((field) => <td key={field} className="whitespace-nowrap px-5 py-3">{formatValue(row[field])}</td>)}</tr>)}</tbody></table></div>}</section>)}</div>}</section>;
}
