import { ArrowRight, BarChart3, BrainCircuit, Building2, BriefcaseBusiness, CircleGauge, Database, Layers3, Network, Play, Sparkles, Workflow } from "lucide-react";
import { Link } from "react-router-dom";

const features=[
 [Building2,"Organizations","A secure home for every company, team, and operating model."],[Layers3,"Workspaces","Keep decisions, initiatives, and collaborators in clear context."],[BrainCircuit,"AI Intelligence","Turn complex questions into executive-ready analysis."],[BriefcaseBusiness,"Commercial Platform","Operate subscriptions, billing, and financial workflows with confidence."],[CircleGauge,"Decision Analysis","Surface trade-offs, risks, and the next best action."],[Network,"Autonomous Reasoning","Connect signals across the business with accountable AI workflows."],[Database,"Knowledge Memory","Build durable organizational intelligence that compounds over time."],[Workflow,"Business Simulation","Model strategic scenarios before committing resources."],
];
function MiniBar({width="70%",tone="blue"}){return <div className={`h-2 rounded-full bg-${tone}-400`} style={{width}}/>}
export default function Landing(){return <main className="landing min-h-screen overflow-hidden bg-[#07090d] text-white">
 <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-8"><Link to="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-500 text-lg shadow-[0_0_32px_rgba(59,130,246,.45)]">A</span><span>Aura <span className="text-slate-400">OS</span></span></Link><div className="hidden items-center gap-7 text-sm text-slate-300 md:flex"><a href="#features">Features</a><a href="#platform">Platform</a><a href="#pricing">Pricing</a><a href="#documentation">Documentation</a></div><Link className="rounded-lg border border-white/15 px-4 py-2 text-sm font-medium transition hover:border-white/35 hover:bg-white/5" to="/login">Login</Link></nav>
 <section className="relative mx-auto max-w-7xl px-6 pb-24 pt-20 text-center lg:px-8 lg:pt-28"><div className="pointer-events-none absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-blue-500/20 blur-[120px]"/><p className="relative mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-blue-400/25 bg-blue-400/10 px-3 py-1 text-xs font-medium text-blue-200"><Sparkles size={14}/> Intelligence, operationalized</p><h1 className="relative mx-auto max-w-4xl text-5xl font-semibold tracking-[-.055em] sm:text-6xl lg:text-7xl">Aura OS</h1><p className="relative mx-auto mt-5 max-w-3xl text-xl font-medium tracking-tight text-slate-200 sm:text-2xl">The Enterprise Operating System for AI-Powered Decision Intelligence.</p><p className="relative mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-400">Build organizations, manage workspaces, collaborate with teams, and make strategic decisions using autonomous AI intelligence.</p><div className="relative mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-5 py-3 font-semibold shadow-lg shadow-blue-500/20 transition hover:bg-blue-400">Launch Aura <ArrowRight size={17}/></Link><a href="#platform" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold transition hover:bg-white/10"><Play size={16}/> Learn More</a></div></section>
 <section id="platform" className="mx-auto max-w-6xl px-6 pb-28 lg:px-8"><div className="rounded-2xl border border-white/10 bg-white/[.045] p-3 shadow-2xl shadow-black/40 backdrop-blur"><div className="overflow-hidden rounded-xl border border-white/10 bg-[#0d1119] p-4 sm:p-6"><div className="mb-6 flex items-center justify-between"><div className="flex gap-2"><i className="h-2.5 w-2.5 rounded-full bg-red-400"/><i className="h-2.5 w-2.5 rounded-full bg-amber-400"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><span className="text-xs text-slate-500">Aura OS / Executive Command</span></div><div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-xl border border-white/10 bg-white/[.035] p-5"><div className="mb-5 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-500/15 text-blue-300"><BrainCircuit size={19}/></span><div><p className="text-sm font-medium">AI Intelligence</p><p className="text-xs text-slate-500">Strategic decision brief</p></div></div><p className="text-sm leading-6 text-slate-300">“Prioritize the enterprise expansion motion while protecting operating margin through staged hiring.”</p><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><div className="rounded-lg bg-white/5 p-3"><p className="text-slate-500">Confidence</p><b className="mt-1 block text-blue-300">94%</b></div><div className="rounded-lg bg-white/5 p-3"><p className="text-slate-500">Risk</p><b className="mt-1 block text-emerald-300">Managed</b></div><div className="rounded-lg bg-white/5 p-3"><p className="text-slate-500">Actions</p><b className="mt-1 block">06</b></div></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-300">Revenue signal</span><BarChart3 size={17} className="text-blue-300"/></div><div className="mt-5 flex h-20 items-end gap-2">{[35,46,42,62,58,76,88].map((h,i)=><span key={i} style={{height:`${h}%`}} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-blue-300/90"/>)}</div></div><div className="rounded-xl border border-white/10 bg-white/[.035] p-5"><p className="text-sm text-slate-300">Active workspaces</p><div className="mt-4 space-y-3">{["Strategy", "Operations", "Growth"].map((item,i)=><div key={item} className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${i===0?'bg-blue-400':'bg-slate-500'}`}/><span className="w-20 text-xs text-slate-400">{item}</span><div className="h-1.5 flex-1 rounded bg-white/10"><MiniBar width={`${75-i*14}%`}/></div></div>)}</div></div></div></div></div></div></section>
 <section id="features" className="border-y border-white/8 bg-white/[.025]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-medium text-blue-300">One operating system</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">The clarity to move the enterprise forward.</h2><p className="mt-4 leading-7 text-slate-400">Aura unifies your organization’s strategic context, intelligence, and execution signals in one considered workspace.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,text])=><article key={title} className="group rounded-2xl border border-white/10 bg-[#0b0e14] p-5 transition hover:-translate-y-1 hover:border-blue-400/35 hover:bg-[#10151f]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><Icon size={19}/></span><h3 className="mt-5 font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></div></section>
 <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-10 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 Aura OS</span><span>Built for deliberate organizations.</span></footer>
 </main>}
