import {
  ArrowRight, BookOpen, BrainCircuit, BriefcaseBusiness, Building2, Check,
  CircleGauge, Code2, Database, FileText, FlaskConical, Layers3, LockKeyhole,
  MessagesSquare, Network, Orbit, ReceiptText, Scale, Sparkles, Users,
} from "lucide-react";
import { Link } from "react-router-dom";

const focus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300 focus-visible:ring-offset-2 focus-visible:ring-offset-[#080b12]";
const frame = "w-full px-5 sm:px-8 lg:px-[clamp(3rem,4vw,6rem)]";
const sectionFrame = frame + " py-[clamp(5rem,8vw,9rem)]";
const personalCapabilities = [
  [MessagesSquare, "Ask anything", "Learn, write, brainstorm, plan, compare, explain, and explore ideas in one natural conversation.", "Available in Alpha", "now"],
  [Scale, "Personal Decisions", "Work through important choices with clearer trade-offs, uncertainty, and grounded recommendations.", "Available in Alpha", "now"],
  [BrainCircuit, "Conversational context", "Continue the conversation without starting over every time.", "Available in Alpha", "now"],
  [BookOpen, "Saved Decisions", "Keep important decisions you want to revisit and record what you eventually choose.", "Available in Alpha", "now"],
  [FileText, "Document intelligence", "Use authorized documents as context when the capability is enabled.", "Limited / Early", "limited"],
  [Orbit, "Current Intelligence", "Aevric AI is being designed to combine verified live information with its reasoning.", "Coming later", "roadmap"],
];
const organizationCapabilities = [
  [Building2, "Organizations", "Create a secure organizational boundary for users, ownership, workspaces, and company context.", "Platform capability / not Personal Alpha"],
  [Layers3, "Workspaces", "Separate teams, initiatives, or operating contexts while preserving access boundaries.", "Platform capability / not Personal Alpha"],
  [BrainCircuit, "Decision Center", "Structured decision analysis for business and strategic questions.", "Business capability / not Personal Alpha"],
  [CircleGauge, "Simulation Center", "Explore modeled scenarios before committing resources or strategies.", "Preserved / not activated for Personal Alpha"],
  [Network, "Marketplace", "A platform area designed for reusable strategies, capabilities, or future intelligence extensions.", "Preserved / inactive for Personal Alpha"],
  [ReceiptText, "Billing", "Commercial infrastructure for plans, subscriptions, invoicing, usage, and future monetization.", "Preserved / inactive for Personal Alpha"],
  [Users, "Members", "Team and member management for shared organizational access.", "Business / Enterprise only"],
  [Database, "Knowledge / Memory", "Organization-scoped context and knowledge retrieval for future Business and Enterprise intelligence.", "Platform capability"],
];
const roadmap = [
  [Orbit, "Current Intelligence", "Verified live information with provenance and citations.", "Roadmap"],
  [Sparkles, "Aevric AI Models", "Aevric AI may adopt self-hosted open-weight and specialized models for proven workloads.", "Long-term roadmap"],
  [FlaskConical, "Aevric AI Model Lab", "Benchmark specialized models for cost, privacy, latency, and quality before moving workloads in-house.", "Post-Alpha roadmap"],
  [Code2, "Aevric AI Developer Platform", "Selected intelligence capabilities could eventually be exposed through APIs and developer tools.", "Future"],
  [BookOpen, "Aevric AI Research", "Future research may explore Personal Intelligence, decision reasoning, grounding, memory, and efficient specialized models.", "Long term"],
  [LockKeyhole, "Enterprise Intelligence", "Organization-wide intelligence, private deployment, stronger governance, and integrated company context.", "Future"],
];

function Status({ children, tone = "quiet" }) {
  const tones = {now:"border-emerald-300/25 bg-emerald-300/10 text-emerald-200",limited:"border-amber-300/20 bg-amber-300/10 text-amber-100",roadmap:"border-violet-300/20 bg-violet-300/10 text-violet-200",quiet:"border-white/10 bg-white/[.04] text-slate-400"};
  return <span className={"inline-flex rounded-full border px-2.5 py-1 text-[.68rem] font-semibold uppercase tracking-[.14em] "+tones[tone]}>{children}</span>;
}
function PublicNav(){return <div className="flex items-center gap-5 text-sm text-slate-300"><a className={focus} href="#personal">Personal</a><a className={focus} href="#platform">Platform</a><a className={focus} href="#future">Future</a><a className={focus} href="#trust">Trust</a></div>;}
function CapabilityCard({item}){const [Icon,title,copy,status,tone]=item;return <article className="rounded-3xl border border-white/10 bg-[#101722]/80 p-6 shadow-[0_24px_80px_rgba(0,0,0,.18)]"><div className="flex items-start justify-between gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-blue-400/10 text-blue-200"><Icon size={20}/></span><Status tone={tone}>{status}</Status></div><h3 className="mt-7 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 leading-7 text-slate-400">{copy}</p></article>;}

export default function LandingVision(){
  return <main className="min-h-screen overflow-hidden bg-[#080b12] text-white">
<nav aria-label="Public navigation" className={"relative z-20 flex flex-wrap items-center justify-between gap-4 py-5 2xl:py-7 "+frame}><Link to="/" className={"flex items-center gap-3 rounded-lg text-lg font-semibold tracking-tight "+focus}><span className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-blue-400 to-indigo-600 shadow-[0_10px_35px_rgba(59,130,246,.28)]">A</span>Aevric AI</Link><div className="hidden lg:block"><PublicNav/></div><div className="flex items-center gap-2"><Link className={"rounded-xl px-4 py-2.5 text-sm font-medium text-slate-300 hover:text-white "+focus} to="/login">Log in</Link><Link className={"rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-blue-100 "+focus} to="/register">Try Aevric AI</Link></div><div className="w-full overflow-x-auto pb-1 lg:hidden"><PublicNav/></div></nav>

<section data-testid="landing-hero" className={"relative grid items-center gap-[clamp(3rem,6vw,8rem)] py-[clamp(3rem,5vw,6rem)] xl:grid-cols-[minmax(0,1.1fr)_minmax(25rem,.9fr)] "+frame}><div className="pointer-events-none absolute -left-40 top-0 h-[32rem] w-[32rem] rounded-full bg-blue-600/15 blur-[130px]"/><div data-testid="hero-copy" className="relative"><Status tone="now">Personal Alpha · Available now</Status><p className="mt-7 text-lg font-semibold text-blue-200">Aevric AI</p><h1 className="mt-3 max-w-[14ch] text-[clamp(3rem,5vw,6.5rem)] font-semibold leading-[.98] tracking-[-.06em]">Understand more.<br/>Decide better.<br/><span className="text-blue-300">Move forward.</span></h1><p className="mt-7 max-w-[42rem] text-[clamp(1.125rem,1.3vw,1.35rem)] leading-8 text-slate-300">Ask Aevric AI anything — learn, write, plan, explore ideas, or work through important decisions with more clarity.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/register" className={"inline-flex items-center gap-2 rounded-2xl bg-blue-500 px-6 py-3.5 font-semibold shadow-[0_16px_45px_rgba(59,130,246,.25)] hover:bg-blue-400 "+focus}>Try Aevric AI <ArrowRight size={18}/></Link><Link to="/login" className={"rounded-2xl border border-white/15 bg-white/[.04] px-6 py-3.5 font-semibold hover:bg-white/[.08] "+focus}>Log in</Link></div><p className="mt-5 text-sm text-slate-500">Personal Alpha available now.</p></div><div aria-label="Personal Aevric AI conversation demonstration" className="relative w-full justify-self-end rounded-[2rem] border border-blue-300/15 bg-gradient-to-b from-[#121a28] to-[#0b1019] p-5 shadow-[0_40px_120px_rgba(0,0,0,.45)] sm:p-7 2xl:p-9"><div className="flex items-center gap-2 border-b border-white/10 pb-5 text-sm font-semibold text-blue-200"><Sparkles size={17}/>Aevric AI</div><div className="ml-auto mt-7 max-w-[85%] rounded-3xl rounded-br-lg bg-blue-500 px-5 py-4 leading-7">I’m thinking about going back to school, but I’m worried about giving up my income.</div><div className="mt-6 max-w-[90%] leading-8 text-slate-300"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Aevric AI</p><p className="mt-2">That sounds like a trade-off between long-term opportunity and financial security. Let’s work through what matters most.</p></div><div className="mt-7 rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-500">A clearer decision</p><p className="mt-3 font-medium text-slate-100">Compare the opportunity, the real cost, and what would make the change sustainable.</p></div></div></section>

<section id="personal" aria-labelledby="personal-heading" className="scroll-mt-8 border-y border-blue-300/10 bg-blue-400/[.035]"><div className={sectionFrame}><div className="max-w-4xl"><p className="text-sm font-semibold text-blue-300">Personal Aevric AI</p><h2 id="personal-heading" className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">One place to think things through.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">Ask questions, explore ideas, work through important decisions, and keep moving with an intelligence built to grow with you.</p></div><div data-testid="personal-capability-grid" className="mt-12 grid auto-rows-fr grid-cols-[repeat(auto-fit,minmax(min(100%,20rem),1fr))] xl:grid-cols-[repeat(auto-fit,minmax(23rem,1fr))] gap-5">{personalCapabilities.map(item=><CapabilityCard key={item[1]} item={item}/>)}</div></div></section>

<section id="platform" aria-labelledby="platform-heading" className="scroll-mt-8"><div className={sectionFrame}><div className="max-w-4xl"><p className="text-sm font-semibold text-slate-400">The Aevric AI platform</p><h2 id="platform-heading" className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">One intelligence platform. Built for more.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Personal is the first public experience. Business and Enterprise remain part of Aevric AI’s architecture and will expand separately over time.</p></div><div data-testid="platform-grid" className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-[1.25fr_1fr_1fr]"><article className="rounded-[2rem] border border-blue-300/20 md:col-span-2 xl:col-span-1 bg-blue-400/[.07] p-7"><Status tone="now">Alpha — Available now</Status><h3 className="mt-7 text-3xl font-semibold">Personal</h3><p className="mt-4 leading-7 text-slate-300">For individuals who want help understanding, thinking, deciding, and moving forward.</p><ul className="mt-7 space-y-3 text-sm text-slate-300">{["Aevric AI","Personal Decisions","Conversation continuity","Grounded reasoning","Saved Decisions"].map(item=><li key={item} className="flex gap-3"><Check className="mt-0.5 text-blue-300" size={16}/>{item}</li>)}</ul><Link to="/register" className={"mt-8 inline-flex items-center gap-2 font-semibold text-blue-200 "+focus}>Try Aevric AI <ArrowRight size={16}/></Link></article><article className="rounded-[2rem] border border-white/10 bg-white/[.025] p-7"><Status tone="limited">Limited / not publicly activated</Status><BriefcaseBusiness className="mt-8 text-slate-400" size={25}/><h3 className="mt-4 text-2xl font-semibold">Business</h3><p className="mt-4 leading-7 text-slate-400">Structured decision intelligence, shared operating context, and company-level tools for organizations.</p><p className="mt-7 text-sm font-medium text-slate-500">Business access later</p></article><article className="rounded-[2rem] border border-white/10 bg-white/[.02] p-7"><Status tone="roadmap">Future / controlled access</Status><LockKeyhole className="mt-8 text-slate-500" size={25}/><h3 className="mt-4 text-2xl font-semibold">Enterprise</h3><p className="mt-4 leading-7 text-slate-400">Built to expand toward stronger governance, security, isolation, administration, integrations, and private deployments.</p></article></div></div></section>

<section aria-labelledby="organizations-heading" className="border-y border-white/8 bg-white/[.018]"><div className={sectionFrame}><div className="max-w-4xl"><p className="text-sm font-semibold text-slate-500">Business and Enterprise architecture</p><h2 id="organizations-heading" className="mt-4 text-4xl font-semibold tracking-[-.04em]">Aevric AI for organizations</h2><p className="mt-5 text-lg text-slate-400">Capabilities built into the broader Aevric AI platform—not activated for Personal Alpha.</p></div><div data-testid="organization-grid" className="mt-12 grid grid-cols-[repeat(auto-fit,minmax(min(100%,17rem),1fr))] xl:grid-cols-[repeat(auto-fit,minmax(24rem,1fr))] gap-x-10 gap-y-12">{organizationCapabilities.map(([Icon,title,copy,status])=><article key={title}><Icon className="text-slate-500" size={22}/><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p><p className="mt-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-600">{status}</p></article>)}</div></div></section>

<section id="future" aria-labelledby="future-heading" className="scroll-mt-8"><div className={sectionFrame}><div className="max-w-4xl"><Status tone="roadmap">Vision / roadmap</Status><h2 id="future-heading" className="mt-6 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Where Aevric AI can go next</h2><p className="mt-5 text-lg leading-8 text-slate-400">Aevric AI is being built so more of its intelligence stack can become Aevric AI-owned over time. These directions are not current Personal Alpha functionality.</p></div><div data-testid="roadmap-grid" className="mt-12 grid grid-cols-[repeat(auto-fit,minmax(min(100%,20rem),1fr))] xl:grid-cols-[repeat(auto-fit,minmax(24rem,1fr))] gap-4">{roadmap.map(([Icon,title,copy,status])=><article key={title} className="rounded-2xl border border-white/8 bg-white/[.02] p-6"><div className="flex items-center justify-between gap-3"><Icon className="text-violet-300/70" size={20}/><Status tone="roadmap">{status}</Status></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>

<section id="trust" aria-labelledby="trust-heading" className="scroll-mt-8 border-y border-white/8 bg-gradient-to-r from-blue-500/[.05] to-violet-500/[.035]"><div className={"grid gap-[clamp(3rem,6vw,7rem)] lg:grid-cols-[.8fr_1.2fr] "+sectionFrame}><div><p className="text-sm font-semibold text-blue-300">How Aevric AI thinks</p><h2 id="trust-heading" className="mt-4 text-4xl font-semibold tracking-[-.04em]">Built for clarity, not just answers.</h2></div><ul className="grid gap-5 sm:grid-cols-2">{["Aevric AI separates natural conversation from important decisions.","Grounded calculations are validated before being presented as facts.","Important Decisions are saved only when you choose.","Personal conversations do not automatically become durable Personal Context.","Current information is not presented as current unless live retrieval is connected."].map(item=><li key={item} className="flex gap-3 leading-7 text-slate-300"><Check className="mt-1 shrink-0 text-blue-300" size={17}/>{item}</li>)}</ul></div></section>

<section className={"text-center "+sectionFrame}><p className="text-sm font-semibold text-blue-300">Personal Alpha</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Start with Aevric AI.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-slate-400">Ask a question. Explore an idea. Work through a decision.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/register" className={"inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3.5 font-semibold text-slate-950 hover:bg-blue-100 "+focus}>Try Aevric AI <ArrowRight size={17}/></Link><Link to="/login" className={"rounded-2xl border border-white/15 px-6 py-3.5 font-semibold "+focus}>Log in</Link></div></section><footer className={"flex flex-col gap-5 border-t border-white/8 py-10 text-sm text-slate-600 sm:flex-row sm:items-center sm:justify-between "+frame}><span>&copy; 2026 Aevric</span><nav aria-label="Footer" className="flex flex-wrap gap-5"><Link to="/" className={"hover:text-white "+focus}>Aevric</Link><Link to="/privacy" className={"hover:text-white "+focus}>Privacy</Link><Link to="/terms" className={"hover:text-white "+focus}>Terms</Link><Link to="/alpha" className={"hover:text-white "+focus}>Private Alpha</Link></nav></footer>
  </main>;
}
