import { MessageSquare, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { consumerText, EmptyState, formatDate, PageHeader, personal, PrimaryLink } from "../components/personal/PersonalUI";
import { listAuraConversations } from "../services/api";

export default function PersonalConversationsPage() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; listAuraConversations().then((rows) => { if (active) setItems(Array.isArray(rows) ? rows : []); }).catch(() => { if (active) setError("We couldn't load your conversations right now."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  return <div className={personal.narrow}><PageHeader eyebrow="Your history" title="Conversations" action={<PrimaryLink to="/intelligence" state={{ newConversation: true }}><Plus size={18}/>New conversation</PrimaryLink>}>Pick up where you left off.</PageHeader>{loading && <p role="status" className="py-12 text-slate-400">Loading conversations…</p>}{error && <p role="alert" className="mt-8 rounded-2xl border border-red-400/20 bg-red-400/[.06] p-5 text-red-200">{error}</p>}{!loading && !error && items.length === 0 && <div className="mt-10"><EmptyState title="Your conversations with Aura will appear here." action={<PrimaryLink to="/intelligence" state={{ newConversation: true }}>Start a conversation</PrimaryLink>}><p>Start with anything you want to understand, plan, or decide.</p></EmptyState></div>}{!loading && !error && items.length > 0 && <section aria-label="Conversation history" className="mt-8 space-y-3">{items.map((item) => <Link key={item.session_id} to="/intelligence" state={{ conversationId: item.session_id }} className={`group grid min-w-0 gap-4 rounded-[24px] border border-white/[.09] bg-[#0d1119] p-5 transition hover:border-blue-300/30 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center sm:p-6 ${personal.focus}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><MessageSquare size={19}/></span><span className="min-w-0"><span className="block truncate text-lg font-semibold text-white">{consumerText(item.title) || "Conversation"}</span>{item.preview && <span className="mt-1 block truncate text-sm text-slate-400">{consumerText(item.preview)}</span>}{Number.isInteger(item.message_count) && <span className="mt-2 block text-xs text-slate-500">{item.message_count} {item.message_count === 1 ? "message" : "messages"}</span>}</span>{item.updated_at && <time className="text-sm text-slate-500">{formatDate(item.updated_at)}</time>}</Link>)}</section>}</div>;
}
