import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { listPersonalDecisions } from "../services/api";

const filters = [["All", null], ["Open", "open"], ["Decided", "decided"], ["Awaiting outcome", "awaiting_outcome"], ["Completed", "completed"]];
const label = (value) => value?.replaceAll("_", " ") || "Open";

export default function PersonalDecisionsPage() {
  const [filter, setFilter] = useState(null); const [decisions, setDecisions] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; listPersonalDecisions(filter).then((items) => { if (active) setDecisions(items); }).catch(() => { if (active) setError("Your decisions could not be loaded. Please try again."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [filter]);
  const selectFilter = (value) => { setLoading(true); setError(""); setFilter(value); };
  return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-sm font-medium text-blue-300">Personal workspace</p><h1 className="mt-1 text-3xl font-bold text-white">My Decisions</h1><p className="mt-2 text-slate-400">Keep the choices you want to revisit, separate from Aevric AI’s recommendation.</p></header><div aria-label="Decision status filters" className="flex flex-wrap gap-2">{filters.map(([name, value]) => <button key={name} onClick={() => selectFilter(value)} aria-pressed={filter === value} className={`rounded-full px-4 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-blue-300 ${filter === value ? "bg-blue-500 text-white" : "bg-white/5 text-slate-300 hover:bg-white/10"}`}>{name}</button>)}</div>{loading && <p role="status" className="text-slate-300">Loading decisions…</p>}{error && <p role="alert" className="rounded-xl bg-red-500/10 p-3 text-red-200">{error}</p>}{!loading && !error && decisions.length === 0 && <section className="rounded-3xl border border-dashed border-white/15 bg-slate-900/60 p-10 text-center"><h2 className="text-xl font-semibold text-white">No saved decisions yet</h2><p className="mt-2 text-slate-400">Ask Aevric AI about a decision when you are ready.</p><Link className="mt-5 inline-flex rounded-xl bg-blue-500 px-4 py-2 font-semibold text-white" to="/intelligence">Ask Aevric AI</Link></section>}{!loading && decisions.length > 0 && <div className="space-y-3">{decisions.map((decision) => <Link key={decision.id} to={`/decisions/${decision.id}`} className="block rounded-2xl border border-white/10 bg-slate-900/70 p-5 transition hover:border-blue-400/40"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-white">{decision.title}</h2><p className="mt-1 text-sm text-slate-400">{label(decision.decision_type)} · {label(decision.status)}</p></div><time className="text-sm text-slate-500">{new Date(decision.updated_at || decision.created_at).toLocaleDateString()}</time></div><p className="mt-3 text-slate-200"><span className="font-medium text-blue-200">Aevric AI recommends:</span> {decision.recommendation}</p>{decision.user_choice && <p className="mt-1 text-slate-300"><span className="font-medium">What I chose:</span> {decision.user_choice}</p>}{decision.review_date && <p className="mt-2 text-sm text-slate-400">Review: {new Date(decision.review_date).toLocaleDateString()}</p>}</Link>)}</div>}</div>;
}
