import { ArrowLeft, CalendarDays } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { formatDate, personal, SectionHeading, StatusPill, truncateTitle } from "../components/personal/PersonalUI";
import { deletePersonalDecision, getPersonalDecision, updatePersonalDecision } from "../services/api";

function FactSection({ title, items }) { const clean = items?.flat().filter(Boolean); if (!clean?.length) return null; return <section className={`${personal.surface} p-6 sm:p-8`}><h2 className={personal.section}>{title}</h2><ul className="mt-5 space-y-3 text-base leading-7 text-slate-300">{clean.map((item) => <li className="flex gap-3" key={typeof item === "string" ? item : JSON.stringify(item)}><span aria-hidden="true" className="mt-3 h-1 w-1 shrink-0 rounded-full bg-blue-300"/>{item}</li>)}</ul></section>; }
function Option({ item }) { return <section className={`${personal.surface} p-6 sm:p-8`}><h3 className="text-xl font-semibold text-white">{item.option}</h3>{item.benefits?.length > 0 && <div className="mt-6"><h4 className="text-sm font-semibold uppercase tracking-[.12em] text-slate-500">Upsides</h4><ul className="mt-3 space-y-2 text-slate-300">{item.benefits.map((value) => <li key={value}>{value}</li>)}</ul></div>}{item.downsides?.length > 0 && <div className="mt-6"><h4 className="text-sm font-semibold uppercase tracking-[.12em] text-slate-500">Trade-offs</h4><ul className="mt-3 space-y-2 text-slate-300">{item.downsides.map((value) => <li key={value}>{value}</li>)}</ul></div>}</section>; }

export default function PersonalDecisionDetailExperience() {
  const { decisionId } = useParams(); const navigate = useNavigate(); const [decision, setDecision] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [choice, setChoice] = useState(""); const [rationale, setRationale] = useState(""); const [reviewDate, setReviewDate] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { getPersonalDecision(decisionId).then((record) => { setDecision(record); setChoice(record.user_choice || ""); setRationale(record.user_choice_rationale || ""); setReviewDate(record.review_date ? record.review_date.slice(0, 10) : ""); }).catch(() => setError("This decision could not be found.")).finally(() => setLoading(false)); }, [decisionId]);
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); try { const record = await updatePersonalDecision(decisionId, { ...(choice.trim() ? { user_choice: choice.trim(), user_choice_rationale: rationale.trim() || null } : {}), review_date: reviewDate || null }); setDecision(record); setChoice(record.user_choice || ""); setRationale(record.user_choice_rationale || ""); } catch { setError("Your changes could not be saved. Please try again."); } finally { setSaving(false); } }
  async function remove() { if (!window.confirm("Delete this saved decision? Your Ask Aura session will remain available.")) return; try { await deletePersonalDecision(decisionId); navigate("/decisions", { replace: true }); } catch { setError("This decision could not be deleted. Please try again."); } }
  if (loading) return <p role="status" className="p-8 text-lg text-slate-300">Loading decision…</p>; if (error && !decision) return <div className={personal.narrow}><p role="alert" className="text-red-200">{error}</p><Link to="/decisions" className="mt-5 inline-block text-blue-300 underline">Back to Decisions</Link></div>;
  const snapshot = decision.analysis_snapshot || {}; const recommendation = decision.recommendation || snapshot.recommendation?.recommended_option || snapshot.recommendation;
  return <div className={personal.narrow}><Link to="/decisions" className={`mt-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white ${personal.focus}`}><ArrowLeft size={16}/>Decisions</Link><header className="pb-10 pt-10 sm:pb-12"><div className="flex flex-wrap items-center gap-3"><StatusPill>{decision.status || "Saved"}</StatusPill>{decision.review_date && <span className="inline-flex items-center gap-2 text-sm text-blue-200"><CalendarDays size={15}/>Review {formatDate(decision.review_date)}</span>}</div><h1 className={`${personal.title} mt-6 max-w-4xl leading-tight`}>{truncateTitle(decision.title, 120)}</h1>{decision.original_question && <section className="mt-8 max-w-4xl border-l-2 border-white/15 pl-5"><p className={personal.eyebrow}>Original decision</p><p className="mt-3 text-lg leading-8 text-slate-300">{decision.original_question}</p></section>}</header>
    <section className="rounded-[32px] border border-blue-300/25 bg-[#101927] p-7 sm:p-10"><p className={personal.eyebrow}>Aura recommended</p><h2 className="mt-4 text-3xl font-semibold text-white sm:text-4xl">{recommendation || "No recommendation recorded"}</h2></section>
    <form onSubmit={save} className="mt-5 rounded-[32px] border border-emerald-200/15 bg-[#101713] p-7 sm:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-emerald-200/80">I chose</p><h2 className="mt-3 text-2xl font-semibold text-white">{choice || "Not decided yet"}</h2></div>{reviewDate && <span className="text-sm text-emerald-100/70">Review {formatDate(reviewDate)}</span>}</div><div className="mt-8 grid gap-5"><label className="text-sm font-medium text-slate-300" htmlFor="user-choice">What did you choose?<textarea id="user-choice" value={choice} onChange={(event) => setChoice(event.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-base text-white outline-none focus:border-emerald-200/50 focus:ring-2 focus:ring-emerald-200/10"/></label><label className="text-sm font-medium text-slate-300" htmlFor="choice-why">Why did you choose it?<textarea id="choice-why" value={rationale} onChange={(event) => setRationale(event.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-base text-white outline-none focus:border-emerald-200/50 focus:ring-2 focus:ring-emerald-200/10"/></label><label className="text-sm font-medium text-slate-300" htmlFor="review-date">When should Aura check back?<input id="review-date" type="date" value={reviewDate} onChange={(event) => setReviewDate(event.target.value)} className="mt-2 block min-h-12 rounded-xl border border-white/10 bg-black/20 px-4 text-white outline-none focus:border-emerald-200/50"/></label>{error && <p role="alert" className="text-red-200">{error}</p>}<button disabled={saving} className={`w-fit rounded-xl bg-white px-5 py-3 font-semibold text-slate-950 hover:bg-slate-200 disabled:opacity-50 ${personal.focus}`}>{saving ? "Saving…" : "Save changes"}</button></div></form>
    <div className="mt-14 space-y-10">{snapshot.alternatives?.length > 0 && <section><SectionHeading>Your options</SectionHeading><div className="grid gap-4 lg:grid-cols-2">{snapshot.alternatives.map((item) => <Option key={item.option} item={item}/>)}</div></section>}<div className="grid gap-4 lg:grid-cols-2"><FactSection title="What Aura knew" items={[snapshot.key_facts || [], snapshot.derived_facts || []]}/><FactSection title="Uncertainties" items={[snapshot.confidence_rationale, snapshot.unresolved_factors || [], snapshot.unresolved_questions || [], snapshot.limitations || []]}/></div><FactSection title="What could change the recommendation" items={snapshot.what_would_change_recommendation || snapshot.recommendation?.what_would_change_the_recommendation}/></div>
    <div className="mt-12 border-t border-white/[.08] pt-7"><button onClick={remove} className={`text-sm text-red-300 underline decoration-red-300/40 underline-offset-4 hover:text-red-200 ${personal.focus}`}>Delete decision</button></div>
  </div>;
}
