import LegalPageLayout, { LegalSection } from "../components/legal/LegalPageLayout";

export default function PrivacyPolicy() {
  return <LegalPageLayout eyebrow="Legal" title="Privacy Policy" intro="This policy explains how Aevric handles information when you use the Aevric AI private Alpha.">
    <LegalSection title="Information we handle"><p>We collect account information you provide, including your name, email address, and password credentials. We also process the prompts, messages, decisions, and other content you submit, along with organization or workspace information you choose to add.</p><p>We may collect operational information needed to run and secure the service, such as session, request, and error information. The current frontend stores an authentication token and limited conversation, session, organization, and workspace context in your browser.</p></LegalSection>
    <LegalSection title="How we use information"><p>We use information to provide and improve Aevric AI, authenticate accounts, generate responses, retrieve relevant current information, preserve features you choose to use, troubleshoot errors, maintain security, and communicate about the Alpha.</p></LegalSection>
    <LegalSection title="Service providers"><p>Aevric uses service providers to operate the Alpha. Depending on the feature used, information may be processed by AI model providers such as OpenAI, current-information and search providers such as Tavily, cloud hosting providers such as Render, and database or infrastructure providers. These providers process information for the services they supply to Aevric and under their own applicable terms.</p><p>Provider processing may occur in jurisdictions outside your own. Aevric does not claim a specific data-residency location for the Alpha.</p></LegalSection>
    <LegalSection title="Sharing"><p>We do not describe Alpha data as being sold. We may disclose information to service providers that help operate Aevric AI, when required by law, to protect the service or its users, or as part of a business transaction subject to appropriate safeguards.</p></LegalSection>
    <LegalSection title="Retention and security"><p>We retain information for as long as reasonably needed to operate and secure the Alpha, meet legal obligations, and resolve disputes. Retention timing may vary by data type and feature. No specific deletion schedule is promised by this policy.</p><p>We use safeguards intended to protect information, but no system is completely secure. Do not submit secrets or highly sensitive information that is unnecessary for your use of the Alpha.</p></LegalSection>
    <LegalSection title="Your choices and requests"><p>You can choose what content to submit and can stop using the Alpha. To ask about access, correction, or deletion of your information, contact aevricai@gmail.com. Availability of particular rights depends on applicable law and technical feasibility during the Alpha.</p></LegalSection>
    <LegalSection title="Children"><p>Aevric AI is not designed for children. If you believe a child has provided personal information, contact us so we can review the situation.</p></LegalSection>
    <LegalSection title="Changes and contact"><p>We may update this policy as the Alpha changes. We will revise the effective date when we make material updates. Privacy questions can be sent to aevricai@gmail.com.</p></LegalSection>
  </LegalPageLayout>;
}
