import LegalPageLayout, { LegalSection } from "../components/legal/LegalPageLayout";

export default function TermsOfUse() {
  return <LegalPageLayout eyebrow="Legal" title="Terms of Use" intro="These Terms govern access to the Aevric AI private Alpha. By creating an account or using the service, you agree to them.">
    <LegalSection title="Private Alpha service"><p>Aevric AI is pre-release software under active development. Features, limits, providers, and availability may change, and the service may contain errors or be interrupted. Access is limited, revocable, and provided for evaluation and feedback.</p></LegalSection>
    <LegalSection title="Accounts"><p>Provide accurate account information, keep credentials confidential, and promptly report suspected unauthorized access. You are responsible for activity through your account and may not share access outside the invited Alpha audience.</p></LegalSection>
    <LegalSection title="Acceptable use"><p>Do not use Aevric AI unlawfully; to harm, deceive, harass, or exploit others; to infringe rights; to distribute malware; to bypass safeguards or access controls; or to disrupt, probe, scrape, reverse engineer, or overload the service except where applicable law expressly permits it.</p></LegalSection>
    <LegalSection title="Your content"><p>You retain rights you have in content you submit. You give Aevric permission to host, copy, transmit, transform, and otherwise process that content only as needed to operate, secure, troubleshoot, and improve the Alpha. You represent that you have the rights needed to submit it.</p></LegalSection>
    <LegalSection title="Aevric materials"><p>Aevric and its licensors retain rights in the service, software, design, branding, and other materials they provide. These Terms give you a limited, non-exclusive, non-transferable right to use the Alpha while your access remains active.</p></LegalSection>
    <LegalSection title="AI outputs and important decisions"><p>AI-generated responses can be incomplete, inaccurate, or unsuitable. Verify important information and use independent professional judgment. Aevric AI is not a substitute for legal, medical, financial, or other qualified professional advice, and you remain responsible for decisions and actions you take.</p></LegalSection>
    <LegalSection title="Third-party services"><p>The Alpha relies on third-party model, search, hosting, database, and infrastructure services. Their availability and processing may affect Aevric AI, and third-party links or sources are governed by their respective terms.</p></LegalSection>
    <LegalSection title="Suspension and termination"><p>Aevric may restrict or end access to protect users or the service, respond to legal requirements, address misuse, or conclude the Alpha. You may stop using the service at any time.</p></LegalSection>
    <LegalSection title="Disclaimers and liability"><p>To the extent permitted by law, the Alpha is provided “as is” and “as available,” without warranties of accuracy, availability, fitness for a particular purpose, or non-infringement. To the extent permitted by law, Aevric will not be liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, profits, or opportunities arising from the Alpha. Mandatory consumer rights are not excluded.</p></LegalSection>
    <LegalSection title="Governing law and contact"><p>These Terms are governed by the laws of the Province of Ontario and the applicable federal laws of Canada. Questions about these Terms can be sent to aevricai@gmail.com.</p></LegalSection>
  </LegalPageLayout>;
}
