import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { LoaderCircle, Send, Sparkles } from "lucide-react";
import { askAura, savePersonalDecision } from "../../services/api";

const errorMessage = (error) => ({ 503: "Aevric AI is temporarily unavailable. Try again shortly.", 504: "This is taking longer than expected. Please try again.", 422: "Aevric AI couldn't produce a reliable recommendation from the available information." }[error?.response?.status] || "Aevric AI couldn't complete this request. Please try again.");

export default function PersonalAsk() {
  const location = useLocation();
  const [message, setMessage] = useState(location.state?.suggestedPrompt || ""); const [result, setResult] = useState(null); const [sessionId, setSessionId] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(null); const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); if (!message.trim() || loading) return; setLoading(true); setError(""); try { const response = await askAura(result?.mode === "CLARIFICATION_REQUIRED" ? { session_id: sessionId, clarification_response: message.trim() } : { message: message.trim() }); setResult(response); setSessionId(response.session_id); setMessage(""); } catch (requestError) { setError(errorMessage(requestError)); } finally { setLoading(false); } }
  async function saveDecision() { if (!sessionId || saving || saved) return; setSaving(true); setError(""); try { setSaved(await savePersonalDecision({ source_session_id: sessionId, decision_type: result.classification })); } catch (requestError) { setError(requestError?.response?.status === 409 ? "This decision is already saved." : "Aevric AI couldn't save this decision. Please try again."); } finally { setSaving(false); } }
  const clarification = result?.mode === "CLARIFICATION_REQUIRED";
  return <div className="mx-auto max-w-4xl space-y-6"><header className="space-y-2"><div className="inline-flex items-center gap-2 text-sm font-medium text-blue-300"><Sparkles size={16}/>Ask Aevric AI</div><h1 className="text-3xl font-bold tracking-tight text-white">What are you trying to figure out?</h1><p className="max-w-2xl text-slate-400">Aevric AI helps you compare the trade-offs and make a decision you can revisit later.</p></header><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-slate-900/70 p-5 shadow-xl"><label className="sr-only" htmlFor="ask-aura-message">Your decision</label><textarea id="ask-aura-message" value={message} onChange={(event) => setMessage(event.target.value)} disabled={loading} placeholder={clarification ? "Share your answer…" : "Describe the decision you are considering…"} className="min-h-36 w-full resize-y rounded-2xl border border-white/10 bg-[#0d111a] p-4 text-slate-100 outline-none placeholder:text-slate-500 focus:border-blue-400 focus:ring-2 focus:ring-blue-500/30 disabled:opacity-60"/><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-400">{clarification ? "Answer Aevric AI's question to continue this decision." : "Your decision is kept in your personal workspace."}</p><button type="submit" disabled={!message.trim() || loading} className="inline-flex items-center gap-2 rounded-xl bg-blue-500 px-5 py-3 font-semibold text-white transition hover:bg-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-300 disabled:cursor-not-allowed disabled:opacity-50"><Send size={16}/>{loading ? "Thinking…" : clarification ? "Continue" : "Ask Aevric AI"}</button></div>{loading && <p role="status" className="mt-4 flex items-center gap-2 text-sm text-blue-200"><LoaderCircle className="animate-spin" size={16}/>Understanding your decision and comparing the trade-offs…</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}</form>{clarification && <section aria-labelledby="clarification-heading" className="rounded-3xl border border-amber-300/20 bg-amber-300/5 p-6"><h2 id="clarification-heading" className="text-lg font-semibold text-amber-100">Before I recommend something, I need to know…</h2><ul className="mt-3 space-y-2 text-slate-200">{result.questions.map((question) => <li key={question}>{question}</li>)}</ul></section>}{result?.mode === "ANALYSIS_COMPLETE" && <AnalysisResult result={result} saved={saved} saving={saving} onSave={saveDecision}/>}</div>;
}

function AnalysisResult({ result, saved, saving, onSave }) { const recommendation = result.recommendation || {}; return <article className="space-y-5 rounded-3xl border border-white/10 bg-slate-900/70 p-6 shadow-xl"><section><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-300">Your decision</p><h2 className="mt-2 text-2xl font-bold text-white">{result.problem_understanding}</h2></section><ListSection title="What matters" items={result.key_facts}/><section><h3 className="text-lg font-semibold text-white">Your options</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{result.alternatives.map((option) => <div key={option.option} className="rounded-2xl border border-white/10 bg-[#0d111a] p-4"><h4 className="font-semibold text-slate-100">{option.option}</h4><ListSection title="Upsides" items={option.benefits} compact/><ListSection title="Trade-offs" items={option.downsides} compact/></div>)}</div></section><section className="rounded-2xl border border-blue-400/30 bg-blue-500/10 p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-200">Aevric AI recommends</p><h3 className="mt-2 text-xl font-bold text-white">{recommendation.recommended_option}</h3><p className="mt-2 text-slate-200">{recommendation.rationale}</p></section><section><h3 className="text-lg font-semibold text-white">Why</h3><p className="mt-2 text-slate-300">{result.analysis}</p></section><section><h3 className="text-lg font-semibold text-white">Confidence</h3><p className="mt-2 text-slate-200">{result.confidence}</p>{result.confidence_rationale?.map((item) => <p key={item} className="text-sm text-slate-400">{item}</p>)}</section><ListSection title="What is still uncertain" items={result.unresolved_questions || result.limitations}/><ListSection title="What could change this" items={result.what_would_change_recommendation}/><ListSection title="Next steps" items={result.prioritized_actions}/>{saved ? <div role="status" className="rounded-2xl bg-emerald-400/10 p-4 text-emerald-100">Decision saved. <Link className="font-semibold underline" to={`/decisions/${saved.id}`}>View decision</Link></div> : <button onClick={onSave} disabled={saving} className="rounded-xl bg-white px-5 py-3 font-semibold text-slate-950 focus:outline-none focus:ring-2 focus:ring-blue-300 disabled:opacity-50">{saving ? "Saving…" : "Save Decision"}</button>}</article>; }
function ListSection({ title, items, compact = false }) { if (!items?.length) return null; return <section className={compact ? "mt-3" : ""}><h3 className={compact ? "text-xs font-semibold uppercase text-slate-400" : "text-lg font-semibold text-white"}>{title}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-300">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
